# Generated by Django 5.2.1 on 2025-05-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
            ],
            options={
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
                (
                    "base_experience",
                    models.IntegerField(default=0, verbose_name="Base experience"),
                ),
                ("height", models.IntegerField(default=0, verbose_name="Height")),
                ("weight", models.IntegerField(default=0, verbose_name="Weight")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "stats",
                    models.ManyToManyField(
                        related_name="pokemon_states", to="pokemon.state"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pokemon_types", to="pokemon.type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemons",
            },
        ),
    ]
