# Generated by Django 5.2.1 on 2025-05-29 18:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
            ],
            options={
                "verbose_name": "Ability",
                "verbose_name_plural": "Abilities",
            },
        ),
        migrations.CreateModel(
            name="MoveBattleStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
            ],
            options={
                "verbose_name": "Move Battle Style",
                "verbose_name_plural": "Move Battle Styles",
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "gender_rate",
                    models.IntegerField(default=0, verbose_name="Gender Rate"),
                ),
                (
                    "capture_rate",
                    models.IntegerField(default=0, verbose_name="Capture Rate"),
                ),
                (
                    "base_happiness",
                    models.IntegerField(default=0, verbose_name="Base Happiness"),
                ),
                (
                    "hatch_counter",
                    models.IntegerField(default=0, verbose_name="Hatch Counter"),
                ),
                ("is_baby", models.BooleanField(default=False, verbose_name="Is Baby")),
                (
                    "is_legendary",
                    models.BooleanField(default=False, verbose_name="Is Legendary"),
                ),
                (
                    "is_mythical",
                    models.BooleanField(default=False, verbose_name="Is Mythical"),
                ),
                (
                    "has_gender_differences",
                    models.BooleanField(
                        default=False, verbose_name="Has Gender Differences"
                    ),
                ),
                (
                    "forms_switchable",
                    models.BooleanField(default=False, verbose_name="Forms Switchable"),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
            ],
            options={
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
                (
                    "double_dmg_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "double_dmg_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "half_dmg_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "half_dmg_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "no_dmg_from",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "no_dmg_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "external_id",
                    models.IntegerField(db_index=True, verbose_name="External id"),
                ),
                (
                    "base_experience",
                    models.IntegerField(default=0, verbose_name="Base experience"),
                ),
                (
                    "image",
                    models.URLField(default=None, null=True, verbose_name="Image url"),
                ),
                ("height", models.IntegerField(default=0, verbose_name="Height")),
                ("weight", models.IntegerField(default=0, verbose_name="Weight")),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "abilities",
                    models.ManyToManyField(
                        related_name="pokemon_abilities", to="pokemon.ability"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemon.species",
                    ),
                ),
                (
                    "stats",
                    models.ManyToManyField(
                        related_name="pokemon_stats", to="pokemon.stat"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="pokemon_types", to="pokemon.type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemons",
            },
        ),
    ]
